package com.huika.cloud.support.db;

import java.util.ArrayList;
import java.util.List;

import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteStatement;

import com.huika.cloud.support.model.City;
import com.huika.cloud.support.model.District;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.Property;
import de.greenrobot.dao.internal.DaoConfig;
import de.greenrobot.dao.internal.SqlUtils;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table District.
*/
public class DistrictDao extends AbstractDao<District, Integer> {

	public static final String TABLENAME = "District";

	/**
	 * Properties of entity District.<br/>
	 * Can be used for QueryBuilder and for referencing column names.
	*/
	public static class Properties {
		public final static Property DistrictID = new Property(0, int.class, "districtID", true, "districtID");
		public final static Property DistrictName = new Property(1, String.class, "districtName", false, "districtName");
		public final static Property CityID = new Property(2, int.class, "cityID", false, "cityID");
	};

	private AddressDaoSession daoSession;

	public DistrictDao(DaoConfig config) {
		super(config);
	}

	public DistrictDao(DaoConfig config, AddressDaoSession daoSession) {
		super(config, daoSession);
		this.daoSession = daoSession;
	}

	/** Creates the underlying database table. */
	public static void createTable(SQLiteDatabase db, boolean ifNotExists) {
		String constraint = ifNotExists ? "IF NOT EXISTS " : "";
		db.execSQL("CREATE TABLE " + constraint + "'District' (" + //
				"'districtID' INTEGER PRIMARY KEY NOT NULL ," + // 0: districtID
				"'districtName' TEXT," + // 1: districtName
				"'cityID' INTEGER NOT NULL );"); // 2: cityID
	}

	/** Drops the underlying database table. */
	public static void dropTable(SQLiteDatabase db, boolean ifExists) {
		String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "'District'";
		db.execSQL(sql);
	}

	/** @inheritdoc */
	@Override
	protected void bindValues(SQLiteStatement stmt, District entity) {
		stmt.clearBindings();
		stmt.bindLong(1, entity.getDistrictID());

		String districtName = entity.getDistrictName();
		if (districtName != null) {
			stmt.bindString(2, districtName);
		}
		stmt.bindLong(3, entity.getCityID());
	}

	@Override
	protected void attachEntity(District entity) {
		super.attachEntity(entity);
		entity.__setDaoSession(daoSession);
	}

	/** @inheritdoc */
	@Override
	public Integer readKey(Cursor cursor, int offset) {
		return cursor.getInt(offset + 0);
	}

	/** @inheritdoc */
	@Override
	public District readEntity(Cursor cursor, int offset) {
		District entity = new District( //
				cursor.getInt(offset + 0), // districtID
				cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // districtName
				cursor.getInt(offset + 2) // cityID
		);
		return entity;
	}

	/** @inheritdoc */
	@Override
	public void readEntity(Cursor cursor, District entity, int offset) {
		entity.setDistrictID(cursor.getInt(offset + 0));
		entity.setDistrictName(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
		entity.setCityID(cursor.getInt(offset + 2));
	}

	/** @inheritdoc */
	@Override
	protected Integer updateKeyAfterInsert(District entity, long rowId) {
		return entity.getDistrictID();
	}

	/** @inheritdoc */
	@Override
	public Integer getKey(District entity) {
		if (entity != null) {
			return entity.getDistrictID();
		}
		else {
			return null;
		}
	}

	/** @inheritdoc */
	@Override
	protected boolean isEntityUpdateable() {
		return true;
	}

	private String selectDeep;

	protected String getSelectDeep() {
		if (selectDeep == null) {
			StringBuilder builder = new StringBuilder("SELECT ");
			SqlUtils.appendColumns(builder, "T", getAllColumns());
			builder.append(',');
			SqlUtils.appendColumns(builder, "T0", daoSession.getCityDao().getAllColumns());
			builder.append(" FROM District T");
			builder.append(" LEFT JOIN CITY T0 ON T.'cityID'=T0.'cityID'");
			builder.append(' ');
			selectDeep = builder.toString();
		}
		return selectDeep;
	}

	protected District loadCurrentDeep(Cursor cursor, boolean lock) {
		District entity = loadCurrent(cursor, 0, lock);
		int offset = getAllColumns().length;

		City city = loadCurrentOther(daoSession.getCityDao(), cursor, offset);
		if (city != null) {
			entity.setCity(city);
		}

		return entity;
	}

	public District loadDeep(Long key) {
		assertSinglePk();
		if (key == null) { return null; }

		StringBuilder builder = new StringBuilder(getSelectDeep());
		builder.append("WHERE ");
		SqlUtils.appendColumnsEqValue(builder, "T", getPkColumns());
		String sql = builder.toString();

		String[] keyArray = new String[] { key.toString() };
		Cursor cursor = db.rawQuery(sql, keyArray);

		try {
			boolean available = cursor.moveToFirst();
			if (!available) {
				return null;
			}
			else if (!cursor.isLast()) { throw new IllegalStateException("Expected unique result, but count was " + cursor.getCount()); }
			return loadCurrentDeep(cursor, true);
		}
		finally {
			cursor.close();
		}
	}

	/** Reads all available rows from the given cursor and returns a list of new ImageTO objects. */
	public List<District> loadAllDeepFromCursor(Cursor cursor) {
		int count = cursor.getCount();
		List<District> list = new ArrayList<District>(count);

		if (cursor.moveToFirst()) {
			if (identityScope != null) {
				identityScope.lock();
				identityScope.reserveRoom(count);
			}
			try {
				do {
					list.add(loadCurrentDeep(cursor, false));
				}
				while (cursor.moveToNext());
			}
			finally {
				if (identityScope != null) {
					identityScope.unlock();
				}
			}
		}
		return list;
	}

	protected List<District> loadDeepAllAndCloseCursor(Cursor cursor) {
		try {
			return loadAllDeepFromCursor(cursor);
		}
		finally {
			cursor.close();
		}
	}

	/** A raw-style query where you can pass any WHERE clause and arguments. */
	public List<District> queryDeep(String where, String... selectionArg) {
		Cursor cursor = db.rawQuery(getSelectDeep() + where, selectionArg);
		return loadDeepAllAndCloseCursor(cursor);
	}

}
