package com.huika.cloud.support.model;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit.
/**
 * Entity mapped to table PROVINCE.
 */
public class Province {

	private int provinceID;
	private String provinceName;

	public Province() {
	}

	public Province(int provinceID) {
		this.provinceID = provinceID;
	}

	public Province(int provinceID, String provinceName) {
		this.provinceID = provinceID;
		this.provinceName = provinceName;
	}

	public int getProvinceID() {
		return provinceID;
	}

	public void setProvinceID(int provinceID) {
		this.provinceID = provinceID;
	}

	public String getProvinceName() {
		return provinceName;
	}

	public void setProvinceName(String provinceName) {
		this.provinceName = provinceName;
	}

}
